image: registry.gitlab.com/mcspr/espurna-travis-test:latest


stages:
    - prepare
    - build


prepare:platformio:
    stage: prepare
    artifacts:
        expire_in: 1h
        paths:
            - platformio
            - espurna
            - ~/.platformio
    script:
        - python -V
        - virtualenv ./platformio
        - . platformio/bin/activate
        - pip install -U platformio
        - git clone --depth=1 https://github.com/xoseperez/espurna
        - python2 prepare.py espurna/code


build:espurna-core-1MB:
     stage: build
     artifacts:
         expire_in: 7d
         paths:
             - espurna/firmware/
     script:
         - . platformio/bin/activate
         - pip freeze
         - pip install -U platformio
         - cd espurna/code && ./build.sh espurna-core-1MB


build:espurna-core-4MB:
     stage: build
     artifacts:
         expire_in: 7d
         paths:
             - espurna/firmware/
     script:
         - . platformio/bin/activate
         - pip freeze
         - pip install -U platformio
         - cd espurna/code && ./build.sh espurna-core-1MB
