image: registry.gitlab.com/mcspr/espurna-travis-test:latest


stages:
    - prepare
    - build
    - package


variables:
    PLATFORMIO_HOME_DIR: "$CI_PROJECT_DIR/platformio"


prepare:platformio:
    stage: prepare
    artifacts:
        expire_in: 1h
        paths:
            - platformio/
            - venv/
            - espurna/
    script:
        - python -V
        - virtualenv ./venv
        - . venv/bin/activate
        - pip install -U platformio
        - git clone --depth=1 https://github.com/xoseperez/espurna
        - python2 prepare.py espurna/code
        - sed -i 's/^node.*gulp.*/echo "...not building web interface"/' espurna/code/build.sh
    only:
        - tags


build:espurna-core-1MB:
    stage: build
    dependencies:
        - prepare:platformio
    artifacts:
        expire_in: 15m
        paths:
            - espurna/firmware/
    script:
        - . venv/bin/activate
        - cd espurna/code && ./build.sh espurna-core-1MB
    only:
        - tags


build:espurna-core-4MB:
    stage: build
    dependencies:
        - prepare:platformio
    artifacts:
        expire_in: 15m
        paths:
            - espurna/firmware/
    script:
        - . venv/bin/activate
        - cd espurna/code && ./build.sh espurna-core-4MB
    only:
        - tags


build:wemos-d1mini-relayshield:
    stage: build
    dependencies:
        - prepare:platformio
    artifacts:
        expire_in: 15m
        paths:
            - espurna/firmware/
    script:
        - . venv/bin/activate
        - cd espurna/code && ./build.sh wemos-d1mini-relayshield
    only:
        - tags


build:wemos-d1mini-relayshield-ssl:
    stage: build
    dependencies:
        - prepare:platformio
    artifacts:
        expire_in: 15m
        paths:
            - espurna/firmware/
    script:
        - . venv/bin/activate
        - cd espurna/code && ./build.sh wemos-d1mini-relayshield-ssl
    only:
        - tags


build:nodemcu-lolin:
    stage: build
    dependencies:
        - prepare:platformio
    artifacts:
        expire_in: 15m
        paths:
            - espurna/firmware/
    script:
        - . venv/bin/activate
        - cd espurna/code && ./build.sh nodemcu-lolin
    only:
        - tags


build:nodemcu-lolin-ssl:
    stage: build
    dependencies:
        - prepare:platformio
    artifacts:
        expire_in: 15m
        paths:
            - espurna/firmware/
    script:
        - . venv/bin/activate
        - cd espurna/code && ./build.sh nodemcu-lolin-ssl
    only:
        - tags


package:release:
    stage: package
    dependencies:
        - build:espurna-core-1MB
        - build:espurna-core-4MB
        - build:wemos-d1mini-relayshield
        - build:wemos-d1mini-relayshield-ssl
        - build:nodemcu-lolin
        - build:nodemcu-lolin-ssl
    artifacts:
        expire_in: 1h
        paths:
            - release.tar.xz
    script:
        - find espurna/firmware
        - tar cJf release.tar.xz espurna/firmware/
    only:
        - tags
