image: registry.gitlab.com/mcspr/espurna-travis-test:latest


stages:
    - prepare
    - build


variables:
    PLATFORMIO_HOME_DIR: "$CI_PROJECT_DIR/platformio"


prepare:platformio:
    stage: prepare
    artifacts:
        expire_in: 1h
        paths:
            - platformio/
            - venv/
            - espurna/
    script:
        - python -V
        - virtualenv ./venv
        - . venv/bin/activate
        - pip install -U platformio
        - git clone --depth=1 https://github.com/xoseperez/espurna
        - python2 prepare.py espurna/code


build:espurna-core-1MB:
     stage: build
     artifacts:
         expire_in: 1h
         paths:
             - espurna/firmware/
     script:
         - . venv/bin/activate
         - cd espurna/code && ./build.sh espurna-core-1MB


build:espurna-core-4MB:
     stage: build
     artifacts:
         expire_in: 7d
         paths:
             - espurna/firmware/
     script:
         - . venv/bin/activate
         - cd espurna/code && ./build.sh espurna-core-1MB
     only:
         - tags
