image: registry.gitlab.com/mcspr/espurna-travis-test:latest

stages:
    - prepare
    - build
    - package

variables:
    PLATFORMIO_HOME_DIR: "$CI_PROJECT_DIR/platformio"
    BUILDER_TOTAL_THREADS: 4

prepare:platformio:
    stage: prepare
    artifacts:
        expire_in: 1h
        paths:
            - platformio/
            - venv/
            - espurna/
            - environment
    script:
        - python -V
        - virtualenv ./venv
        - . venv/bin/activate
        - mkdir -p espurna
        - pushd espurna && git init && git remote add origin https://github.com/xoseperez/espurna && popd
        - pip install -U requests
        - python2 prepare_env.py && cat environment && source environment
        - pushd espurna && git fetch --depth=1 origin refs/heads/dev && git checkout FETCH_HEAD && popd
        - "[[ ${ESPURNA_DO_RELEASE} = \"True\" ]] || exit 10"
        - pip install -U platformio
        - python2 prepare.py espurna/code
    only:
        - schedules

build:template: &build_template
    stage: build
    dependencies:
        - prepare:platformio
    artifacts:
        expire_in: 15m
        paths:
            - espurna/firmware/
    script:
        - . venv/bin/activate
        - ./build.sh
    only:
        - schedules

build:builder_0:
    variables:
        BUILDER_THREAD: 0
    <<: *build_template

build:builder_1:
    variables:
        BUILDER_THREAD: 1
    <<: *build_template

build:builder_2:
    variables:
        BUILDER_THREAD: 2
    <<: *build_template

build:builder_3:
    variables:
        BUILDER_THREAD: 3
    <<: *build_template

package:release:
    stage: package
    dependencies:
        - build:builder_0
        - build:builder_1
        - build:builder_2
        - build:builder_3
    artifacts:
        expire_in: 1h
        paths:
            - release.tar.xz
    script:
        - tar cJf release.tar.xz espurna/firmware/
        - source environment
        - cd espurna/firmware/*
        - ghr -r mcspr/espurna-travis-test -b ${ESPURNA_RELEASE_BODY} ${ESPURNA_RELEASE_TAG} ./
    only:
        - schedules
