stages:
    - prepare-pio
    - prepare-build
    - build


before_script:
    - export DEBIAN_FRONTEND=noninteractive

      
prepare-pio:
    stage: prepare-pio
    artifacts:
        paths:
            - platformio
    script:
        - apt-get update -qq && apt-get install -y -qq nodejs python2-virtualenv python2-pip
        - virtualenv ./platformio
        - python -V


prepare-build:
    stage: prepare-build
    artifacts:
        paths:
            - espurna/code/node_modules
            - espurna/code/.piolibdeps
            - espurna/.platformio
    script:
        - . platformio/bin/activate
        - pip install -U platformio
        - git clone --depth=1 https://github.com/xoseperez/espurna
        - python2 prepare.py
        - cd espurna/code && npm install --only=dev


build:espurna-core-1MB:
     stage: build
     artifacts:
         paths:
             - espurna/firmware/
     script:
         - . platformio/bin/activate
         - cd espurna/code
         - ./build.sh espurna-core-1MB


build:espurna-core-4MB:
     stage: build
     artifacts:
         paths:
             - espurna/firmware/
     script:
         - . platformio/bin/activate
         - cd espurna/code
         - ./build.sh espurna-core-4MB
