image: node:8-stretch

stages:
    - prepare-pio
    - prepare-build
    - build


before_script:
    - export DEBIAN_FRONTEND=noninteractive

      
prepare-pio:
    stage: prepare-pio
    artifacts:
        paths:
            - platformio
    script:
        - apt-get update -qq && apt-get install -y -qq python-virtualenv python-pip
        - virtualenv ./platformio
        - python -V
        - pip install -U platformio


prepare-build:
    stage: prepare-build
    artifacts:
        paths:
            - espurna
            - .platformio
    script:
        - . platformio/bin/activate
        - git clone --depth=1 https://github.com/xoseperez/espurna
        - python2 prepare.py espurna/code


build:espurna-core-1MB:
     stage: build
     artifacts:
         paths:
             - espurna/firmware/
     script:
         - . platformio/bin/activate
         - cd espurna/code
         - ./build.sh espurna-core-1MB


build:espurna-core-4MB:
     stage: build
     artifacts:
         paths:
             - espurna/firmware/
     script:
         - . platformio/bin/activate
         - cd espurna/code
         - ./build.sh espurna-core-4MB
