sudo: false
language: python
python:
- '2.7'

env:
  global:
  - ESPURNA_COMMIT=87859c5ad89e2544cb2d65882f25185bc167528a
  - PLATFORMIO_LIBDEPS_DIR="${HOME}/pio-libdeps"
  - BUILDER_TOTAL_THREADS=4

cache:
  directories:
  - ${HOME}/.npm
  - ${HOME}/.cache/pip
  - ${HOME}/.platformio
  - ${HOME}/pio-libdeps
  - ${HOME}/espurna/code/node_modules

install:
  - env | grep TRAVIS
  - pip install -U platformio
  - mkdir -p espurna/code/node_modules
  - pushd espurna
  - git init
  - git remote add origin https://github.com/xoseperez/espurna
  - git fetch --depth=1 origin $ESPURNA_COMMIT
  - git checkout FETCH_HEAD
  - |
    pushd code
    sed -i 's/environments=$travis/environments=$available/' build.sh
    if [ ! -e node_modules/gulp/bin/gulp.js ] ; then
        npm install --only=dev
    fi
    popd -n
    popd

# XXX override deploy target repo XXX
#before_deploy:
#  - export TRAVIS_REPO_SLUG=mcspr/espurna

deploy:
  provider: releases
  api_key:
    secure: Plq6C7sY/OBNp9OEszlsRKr1A6ezmYNiFHoxb6QN0rs96BEBjRKDfa9yGQus2O+42zxnPgcGWBPVUQ20hY1NQ1/+YFjrXabmAKqfSV1lTUuy2XOh2UQBE2wwiRfK2Ej4qmecMvqsaKEVEtCgcWU4Ozm/sfTZYBCpkeUcqWKZTzulKKE4Z+R8mE/CgbbyS+E3SxCoydKeSclg9WKzjPy8K6MHvi/rsvjmbEMq81QItfcVeRteclV7mYPCmshxQPNKH9bZ9kQmwrWX2GzS6H9fKwu+o1LdvpVE3GEmWl1iWpGzmnakWUMa7y4+IWM0YTG83Zmqd18CUqiuDdhtho5MXR/iY9HpM1FsQ4fYXeGEtlHwzT4TvX3B6brI34v1ycwbvE7QUFy5GWRNJOZNuuG/ym5YnctMCsIw263kTds6zL7cWV90/WJsoTEpicMdcCmECCHmnliz08QgdnO78mjJ3+Z/tuued6jfpRSiReNAbsXmI+vy+w9x84824O1kmZWmI1mhizIUmsV48Jz3rsMXGnxhCHrzJLduKYEwD24ngLikZKhCMNyNoRYTYpcnF33v/Bz+sqI7QhkU6/onNEoLyL/i6wQF10hkOZ9NBS13hK71svHHX24rmIC6N6OFxO9NYgwgy8poMWuZHxTJOWwe8YR2GcY9ChnEQLeY8cZf2rM=
  file_glob: true
  file: espurna/firmware/**/*
  skip_cleanup: true
  on:
    branch: builder
    repo: mcspr/espurna-travis-test
    tags: true
    condition: $TRAVIS_EVENT_TYPE = push

stages:
  - name: "Test"
    if: type IN (push, pull_request) AND tag IS NOT present
  - name: "Release"
    if: tag IS present

script:
  - bash build.sh -p

jobs:
  include:
  - stage: "Test"
    script: cd espurna/code && bash build.sh travis01
  - script: cd espurna/code && bash build.sh travis02
  - script: cd espurna/code && bash build.sh travis03
  - stage: "Release"
    env: BUILDER_THREAD=0
  - env: BUILDER_THREAD=1
  - env: BUILDER_THREAD=2
  - env: BUILDER_THREAD=3
