sudo: false
language: python
python:
- '2.7'

env:
  global:
  - ESPURNA_COMMIT=0c657a4a4a41d2b2ddb0dc36e08511775f284c0f
  - PLATFORMIO_LIBDEPS_DIR="${HOME}/pio-libdeps"

cache:
  directories:
  - ${HOME}/.cache/pip
  - ${HOME}/.platformio
  - ${HOME}/pio-libdeps

install:
  - pip install -U platformio
  - rm -rf espurna && mkdir espurna
  - cd espurna && git init
  - git remote add origin https://github.com/xoseperez/espurna
  - git fetch --depth=1 origin $ESPURNA_COMMIT
  - git checkout FETCH_HEAD && cd ..

deploy:
  provider: releases
  api_key:
    secure: dr3HsQVYSFTT2Y5xSzIn5WtmRTVHCcU9hr9Vcnj3npsh9FeZrH9HdtrcX3FWCVxXwcwTenc87syL7PT36J1EXjLfEl/eMC11rR4lQMD+GnlH8wrrAIT3yYwY9PLnHrtSHMBHJ79jyjaAmOD5Iv3AtLJCtmwz4spbSD/nmcESd/DM3gemQFOT0K6e+cA1otSSlBswlEzoMsHpMrwFJrRXUDjePG+Z9yuYpRDX+IYw5o3n0WN+nWx6Y8/O4Gh/DUnwUOfN/xvmbuKK7TUKxDnPCCFj7s69qZcAzkPwVaUXuu7g4pYIlRRBy2TbKFsowBmWB+n758Z2Px5yPA2YDXIqa+C+TFuHnYXiTSBo26x0Yi0h0BZmUXlujwoKv97BiGLjZv6rAr66qc51Dfsd9K6Cu5e6DbhjI+osi+Xwv1sSvJnLbssIMDHmbjINApJXDTGfq/fsZUIzY8F7HI4dGK1Og7nm+gDadnVj1CfyVcrIrNcDjzTg4JJuzS+FfRNPvOEqf/AG1dS9DoyOfIT7ASMOzwo7vVM1sseIeHx9u7cWgp9cfgh3zQkGfdUbqaBvbAQqPCkKu97Psw1rAAV+o42HPtIQxBYVXyR4jbjQ7fDA15m4PcCU6l4M4jJS/88iRhS1knUSuBj9zeNwfs1Tl9UkstBfBfB+DQG1u+/kH8mfi+E=
  file_glob: true
  file: espurna/firmware/**/*
  skip_cleanup: true
  on:
    repo: mcspr/espurna-travis-test
    branch: builder
    tags: true

after_script:
  - rm -rf espurna/firmware/
  - rm -rf espurna/code/.pioenvs

stages:
  - name: "release"
    if: tag IS present

jobs:
  fast_finish: true
  include:
  - script: ./build.sh espurna-core-1MB
    stage: "release"
  - script: ./build.sh espurna-core-4MB
  - script: ./build.sh wemos-d1mini-relayshield
  - script: ./build.sh wemos-d1mini-relayshield-ssl
  - script: ./build.sh nodemcu-lolin
  - script: ./build.sh nodemcu-lolin-ssl
  - script: ./build.sh tinkerman-espurna-h06
  - script: ./build.sh tinkerman-espurna-h08
  - script: ./build.sh tinkerman-espurna-switch
  - script: ./build.sh wemos-d1-tarpunashield
  - script: ./build.sh itead-sonoff-basic
  - script: ./build.sh itead-sonoff-basic-dht
  - script: ./build.sh itead-sonoff-basic-dallas
  - script: ./build.sh itead-sonoff-rf
  - script: ./build.sh itead-sonoff-th
  - script: ./build.sh itead-sonoff-pow
  - script: ./build.sh itead-sonoff-pow-r2
  - script: ./build.sh itead-sonoff-dual
  - script: ./build.sh itead-sonoff-dual-r2
  - script: ./build.sh itead-sonoff-dual-ota-r2
  - script: ./build.sh itead-sonoff-4ch
  - script: ./build.sh itead-sonoff-4ch-pro
  - script: ./build.sh itead-sonoff-touch
  - script: ./build.sh itead-sonoff-b1
  - script: ./build.sh itead-sonoff-t1-1ch
  - script: ./build.sh itead-sonoff-t1-2ch
  - script: ./build.sh itead-sonoff-t1-3ch
  - script: ./build.sh itead-sonoff-led
  - script: ./build.sh itead-sonoff-rfbridge
  - script: ./build.sh itead-sonoff-rfbridge-direct
  - script: ./build.sh itead-slampher
  - script: ./build.sh itead-s20
  - script: ./build.sh itead-1ch-inching
  - script: ./build.sh itead-motor
  - script: ./build.sh itead-sonoff-sv
  - script: ./build.sh itead-sonoff-s31
  - script: ./build.sh electrodragon-wifi-iot
  - script: ./build.sh workchoice-ecoplug
  - script: ./build.sh jangoe-wifi-relay-nc
  - script: ./build.sh jangoe-wifi-relay-no
  - script: ./build.sh openenergymonitor-mqtt-relay
  - script: ./build.sh jorgegarcia-wifi-relays
  - script: ./build.sh aithinker-ai-light
  - script: ./build.sh magichome-led-controller
  - script: ./build.sh magichome-led-controller-20
  - script: ./build.sh huacanxing-h801
  - script: ./build.sh huacanxing-h802
  - script: ./build.sh arilux-al-lc01
  - script: ./build.sh arilux-al-lc02
  - script: ./build.sh arilux-al-lc06
  - script: ./build.sh arilux-al-lc11
  - script: ./build.sh arilux-e27
  - script: ./build.sh itead-bnsz01
  - script: ./build.sh wion-50055
  - script: ./build.sh exs-wifi-relay-v31
  - script: ./build.sh wemos-v9261f
  - script: ./build.sh esp01-v9261f
  - script: ./build.sh wemos-ech1560
  - script: ./build.sh esp01-ech1560
  - script: ./build.sh mancavemade-esplive
  - script: ./build.sh intermittech-quinled
  - script: ./build.sh xenon-sm-pw702u
  - script: ./build.sh authometion-lyt8266
  - script: ./build.sh kmc-70011
  - script: ./build.sh yjzk-switch-2ch
  - script: ./build.sh generic-8ch
  - script: ./build.sh gizwits-witty-cloud
  - script: ./build.sh euromate-wifi-stecker-shuko
  - script: ./build.sh tonbux-powerstrip02
  - script: ./build.sh lingan-swa1
  - script: ./build.sh stm-relay
  - script: ./build.sh heygo-hy02
  - script: ./build.sh maxcio-wus002s
  - script: ./build.sh yidian-xsssa05
  - script: ./build.sh tonbux-xsssa06
  - script: ./build.sh green-esp8266relay
  - script: ./build.sh ike-espike
  - script: ./build.sh arniex-swifitch
  - script: ./build.sh zhilde-eu44-w
  - script: ./build.sh luani-hvio
  - script: ./build.sh neo-coolcam-power-plug-wifi
  - script: ./build.sh estink-wifi-power-strip
  - script: ./build.sh generic-esp01s-relay-40
  - script: ./build.sh generic-esp01s-rgbled-10
  - script: ./build.sh generic-esp01s-dht11-10
  - script: ./build.sh generic-esp01s-ds18b20-10
  - script: ./build.sh heltec-touch-relay
  - script: ./build.sh allnet-4duino-iot-wlan-relais
  - script: ./build.sh tonbux-mosquito-killer
  - script: ./build.sh pilotak-esp-din-v1
  - script: ./build.sh nodemcu-geiger
