language: python
dist: focal
python:
- '3.8'

env:
  global:
  - BUILDER_TOTAL_THREADS=4

cache:
  directories:
  - ${HOME}/.npm
  - ${HOME}/.cache/pip
  - ${HOME}/.platformio

install:
  - env | grep TRAVIS
  - set -e
  - |
    pip install -U platformio
    pio upgrade --dev
  - pio platform update -p
  - npm install -g npm@latest
  - |
    pip install .
    if [ ${TRAVIS_BUILD_STAGE_NAME} = "Test" ]; then
        espurna_nightly prepare xoseperez/espurna
        exit $?
    fi
    if [ ${TRAVIS_BUILD_STAGE_NAME} = "Release" ]; then
        espurna_nightly mkenv xoseperez/espurna
        source environment
    fi
  - |
    git init espurna
    pushd espurna
    git remote add origin ${NIGHTLY_TARGET_REPO_URL}
    git fetch --depth=1 origin ${NIGHTLY_TARGET_COMMIT_SHA}
    git checkout FETCH_HEAD
    popd
  - |
    pushd espurna/code
    npm ci
    popd
  - set +e

before_deploy:
    - espurna_nightly rename_releases --sha ${NIGHTLY_TARGET_COMMIT_SHA} espurna/firmware

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: espurna/firmware/**/*
  overwrite: true
  skip_cleanup: true
  target_commitish: ${NIGHTLY_BUILDER_COMMIT_SHA}
  release_number: ${NIGHTLY_BUILDER_RELEASE_NUMBER}
  on:
    branch: builder
    repo: mcspr/espurna-nightly-builder
    condition: $TRAVIS_BUILD_STAGE_NAME = Release

stages:
  - name: "Test"
  - name: "Release"
    if: type IN (cron, api)

script:
  - |
    set -e
    pushd espurna/code
    TRAVIS_COMMIT=$NIGHTLY_TARGET_COMMIT_SHA ./build.sh -r
    popd
    set +e

jobs:
  include:
  - stage: "Test"
    script: true
  - stage: "Release"
    env: BUILDER_THREAD=0
  - env: BUILDER_THREAD=1
  - env: BUILDER_THREAD=2
  - env: BUILDER_THREAD=3

notifications:
  email: false
