sudo: false
conditions: v1
language: python
python:
- '2.7'

env:
  global:
  - PLATFORMIO_LIBDEPS_DIR="${HOME}/pio-libdeps"
  - BUILDER_TOTAL_THREADS=4

cache:
  directories:
  - ${HOME}/.npm
  - ${HOME}/.cache/pip
  - ${HOME}/.platformio
  - ${HOME}/pio-libdeps
  - ${HOME}/espurna/code/node_modules

install:
  - env | grep TRAVIS
  - |
    pip install .
    if [ ${TRAVIS_BUILD_STAGE_NAME} = "Test" ]; then
        python -mespurna_dev_builder prepare xoseperez/espurna mcspr/espurna-travis-test
        exit $?
    fi
    if [ ${TRAVIS_BUILD_STAGE_NAME} = "Release" ]; then
        python -mespurna_dev_builder mkenv mcspr/espurna-travis-test
        source environment
    fi
  - git clone --branch dev --no-tags --single-branch --depth=1 https://github.com/xoseperez/espurna
  - |
    pushd espurna/code
    pip install -U platformio
    mkdir -p node_modules
    if [ ! -e node_modules/gulp/bin/gulp.js ] ; then
        npm install --only=dev
    fi
    popd

# XXX override deploy target repo XXX
#before_deploy:
#  - export TRAVIS_REPO_SLUG=mcspr/espurna

before_deploy:
    - bash rename_app_revision.sh

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: espurna/firmware/**/*
  overwrite: true
  skip_cleanup: true
  release_number: ${TRAVIS_RELEASE_NUMBER}
  on:
    branch: builder
    repo: mcspr/espurna-travis-test
    condition: $TRAVIS_BUILD_STAGE_NAME = Release

stages:
  - name: "Test"
  - name: "Release"
    if: type IN (cron, api)

script:
  - pushd espurna/code && bash build.sh -p && popd

jobs:
  include:
  - stage: "Test"
    script: true
  - stage: "Release"
    env: BUILDER_THREAD=0
  - env: BUILDER_THREAD=1
  - env: BUILDER_THREAD=2
  - env: BUILDER_THREAD=3

notifications:
  email: false
