sudo: false
language: python
python:
- '2.7'

env:
  global:
  - PLATFORMIO_LIBDEPS_DIR="${HOME}/pio-libdeps"
  - BUILDER_TOTAL_THREADS=4

cache:
  directories:
  - ${HOME}/.npm
  - ${HOME}/.cache/pip
  - ${HOME}/.platformio
  - ${HOME}/pio-libdeps
  - ${HOME}/espurna/code/node_modules

install:
  - env | grep TRAVIS
  - |
    pushd espurna
    git init
    git remote add origin https://github.com/xoseperez/espurna
    popd
  - |
    pip install -U requests
    python prepare_env.py
    source environment
    [[ ${ESPURNA_DO_RELEASE} = "False" ]] && exit
    export ESPURNA_RELEASE_BODY="https://github.com/xoseperez/espurna/commit/${ESPURNA_COMMIT}"
  - |
    pushd espurna
    git fetch --depth=1 origin $ESPURNA_COMMIT
    git checkout FETCH_HEAD
    popd
  - |
    pushd esurna/code
    pip install -U platformio
    mkdir -p node_modules
    if [ ! -e node_modules/gulp/bin/gulp.js ] ; then
        npm install --only=dev
    fi
    popd

# XXX override deploy target repo XXX
#before_deploy:
#  - export TRAVIS_REPO_SLUG=mcspr/espurna

before_deploy:
    - git config --local user.name "espurna-travis-test"
    - git config --local user.email "prokhorov.max@outlook.com"
    - git tag $(date -u +%Y%m%d)

deploy:
  provider: releases
  api_key:
    secure: Plq6C7sY/OBNp9OEszlsRKr1A6ezmYNiFHoxb6QN0rs96BEBjRKDfa9yGQus2O+42zxnPgcGWBPVUQ20hY1NQ1/+YFjrXabmAKqfSV1lTUuy2XOh2UQBE2wwiRfK2Ej4qmecMvqsaKEVEtCgcWU4Ozm/sfTZYBCpkeUcqWKZTzulKKE4Z+R8mE/CgbbyS+E3SxCoydKeSclg9WKzjPy8K6MHvi/rsvjmbEMq81QItfcVeRteclV7mYPCmshxQPNKH9bZ9kQmwrWX2GzS6H9fKwu+o1LdvpVE3GEmWl1iWpGzmnakWUMa7y4+IWM0YTG83Zmqd18CUqiuDdhtho5MXR/iY9HpM1FsQ4fYXeGEtlHwzT4TvX3B6brI34v1ycwbvE7QUFy5GWRNJOZNuuG/ym5YnctMCsIw263kTds6zL7cWV90/WJsoTEpicMdcCmECCHmnliz08QgdnO78mjJ3+Z/tuued6jfpRSiReNAbsXmI+vy+w9x84824O1kmZWmI1mhizIUmsV48Jz3rsMXGnxhCHrzJLduKYEwD24ngLikZKhCMNyNoRYTYpcnF33v/Bz+sqI7QhkU6/onNEoLyL/i6wQF10hkOZ9NBS13hK71svHHX24rmIC6N6OFxO9NYgwgy8poMWuZHxTJOWwe8YR2GcY9ChnEQLeY8cZf2rM=
  file_glob: true
  file: espurna/firmware/**/*
  skip_cleanup: true
  body: ${ESPURNA_RELEASE_BODY}
  on:
    branch: builder
    repo: mcspr/espurna-travis-test
    tags: false
    condition: $TRAVIS_EVENT_TYPE = cron

stages:
  - name: "Test"
    if: type = push
  - name: "Release"
    if: type = cron

script:
  - bash build.sh -p

jobs:
  include:
  - stage: "Test"
    script:
      - echo ${ESPURNA_COMMIT}
      - echo ${ESPURNA_RELEASE_BODY}
      - echo ${ESPURNA_DO_RELEASE}
  - stage: "Release"
    env: BUILDER_THREAD=0
  - env: BUILDER_THREAD=1
  - env: BUILDER_THREAD=2
  - env: BUILDER_THREAD=3
