sudo: false
conditions: v1
language: python
python:
- '2.7'

env:
  global:
  - PLATFORMIO_LIBDEPS_DIR="${HOME}/pio-libdeps"
  - BUILDER_TOTAL_THREADS=4

cache:
  directories:
  - ${HOME}/.npm
  - ${HOME}/.cache/pip
  - ${HOME}/.platformio
  - ${HOME}/pio-libdeps
  - ${HOME}/espurna/code/node_modules

install:
  - env | grep TRAVIS
  - |
    pip install .
    if [ ${TRAVIS_BUILD_STAGE_NAME} = "Test" ]; then
        espurna_nightly prepare xoseperez/espurna
        exit $?
    fi
    if [ ${TRAVIS_BUILD_STAGE_NAME} = "Release" ]; then
        espurna_nightly mkenv xoseperez/espurna
        source environment
    fi
  - |
    git init espurna
    pushd espurna
    git remote add origin ${NIGHTLY_TARGET_REPO_URL}
    git fetch --depth=1 origin ${NIGHTLY_COMMIT_SHA}
    git checkout FETCH_HEAD
    popd
  - |
    pushd espurna/code
    pip install -U platformio
    mkdir -p node_modules
    if [ ! -e node_modules/gulp/bin/gulp.js ] ; then
        npm install --only=dev
    fi
    popd

# XXX override deploy target repo XXX
#before_deploy:
#  - export TRAVIS_REPO_SLUG=mcspr/espurna

before_deploy:
    - espurna_nightly rename_releases --sha ${NIGHTLY_COMMIT_SHA} espurna/firmware

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: espurna/firmware/**/*
  overwrite: true
  skip_cleanup: true
  release_number: ${NIGHTLY_RELEASE_NUMBER}
  on:
    branch: builder
    repo: mcspr/espurna-nightly-builder
    condition: $TRAVIS_BUILD_STAGE_NAME = Release

stages:
  - name: "Test"
  - name: "Release"
    if: type IN (cron, api)

script:
  - pushd espurna/code && bash build.sh -p && popd

jobs:
  include:
  - stage: "Test"
    script: true
  - stage: "Release"
    env: BUILDER_THREAD=0
  - env: BUILDER_THREAD=1
  - env: BUILDER_THREAD=2
  - env: BUILDER_THREAD=3

notifications:
  email: false
