sudo: false
language: python
python:
- '2.7'

env:
  global:
  - ESPURNA_COMMIT=87859c5ad89e2544cb2d65882f25185bc167528a
  - PLATFORMIO_LIBDEPS_DIR="${HOME}/pio-libdeps"
  - BUILDER_TOTAL_THREADS=4

cache:
  directories:
  - ${HOME}/.npm
  - ${HOME}/.cache/pip
  - ${HOME}/.platformio
  - ${HOME}/pio-libdeps
  - ${HOME}/espurna/code/node_modules

install:
  - env | grep TRAVIS
  - pip install -U platformio
  - mkdir -p espurna/code/node_modules
  - pushd espurna
  - git init
  - git remote add origin https://github.com/xoseperez/espurna
  - git fetch --depth=1 origin $ESPURNA_COMMIT
  - git checkout FETCH_HEAD
  - |
    pushd code
    sed -i 's/environments=$travis/environments=$available/' build.sh
    if [ ! -e node_modules/gulp/bin/gulp.js ] ; then
        npm install --only=dev
    fi
    popd -n
    popd

# XXX override deploy target repo XXX
#before_deploy:
#  - export TRAVIS_REPO_SLUG=mcspr/espurna

deploy:
  provider: releases
  api_key:
    secure: dr3HsQVYSFTT2Y5xSzIn5WtmRTVHCcU9hr9Vcnj3npsh9FeZrH9HdtrcX3FWCVxXwcwTenc87syL7PT36J1EXjLfEl/eMC11rR4lQMD+GnlH8wrrAIT3yYwY9PLnHrtSHMBHJ79jyjaAmOD5Iv3AtLJCtmwz4spbSD/nmcESd/DM3gemQFOT0K6e+cA1otSSlBswlEzoMsHpMrwFJrRXUDjePG+Z9yuYpRDX+IYw5o3n0WN+nWx6Y8/O4Gh/DUnwUOfN/xvmbuKK7TUKxDnPCCFj7s69qZcAzkPwVaUXuu7g4pYIlRRBy2TbKFsowBmWB+n758Z2Px5yPA2YDXIqa+C+TFuHnYXiTSBo26x0Yi0h0BZmUXlujwoKv97BiGLjZv6rAr66qc51Dfsd9K6Cu5e6DbhjI+osi+Xwv1sSvJnLbssIMDHmbjINApJXDTGfq/fsZUIzY8F7HI4dGK1Og7nm+gDadnVj1CfyVcrIrNcDjzTg4JJuzS+FfRNPvOEqf/AG1dS9DoyOfIT7ASMOzwo7vVM1sseIeHx9u7cWgp9cfgh3zQkGfdUbqaBvbAQqPCkKu97Psw1rAAV+o42HPtIQxBYVXyR4jbjQ7fDA15m4PcCU6l4M4jJS/88iRhS1knUSuBj9zeNwfs1Tl9UkstBfBfB+DQG1u+/kH8mfi+E=
  file_glob: true
  file: espurna/firmware/**/*
  skip_cleanup: true
  on:
    branch: builder
    repo: mcspr/espurna-travis-test
    tags: true
    condition: $TRAVIS_EVENT_TYPE = push

stages:
  - name: "Test"
    if: type IN (push, pull_request) AND tag IS NOT present
  - name: "Release"
    if: tag IS present

script:
  - cd espurna/code && bash build.sh -p

jobs:
  include:
  - stage: "Test"
    script: cd espurna/code && bash build.sh travis01
  - script: cd espurna/code && bash build.sh travis02
  - script: cd espurna/code && bash build.sh travis03
  - stage: "Release"
    env: BUILDER_THREAD=0
  - env: BUILDER_THREAD=1
  - env: BUILDER_THREAD=2
  - env: BUILDER_THREAD=3
