blank_issues_enabled: true
contact_links:
  - name: ESPurna Wiki
    url: https://github.com/xoseperez/espurna/wiki
    about: Documentation related to the ESPurna project.
  - name: ESPurna issue tracker
    url: https://github.com/xoseperez/espurna/issues
    about: Report any issues with the specific firmware version or documentation here.
  - name: Gitter chat
    url: https://gitter.im/tinkerman-cat/espurna
    about: A less formal way to ask a question.
