#on:
#  schedule:
#    cron: '0 7 * * *'

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Repo to compare with'
        required: true
        default: xoseperez/espurna

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: actions/checkout@v2
        with:
          ref: builder

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py', 'setup.cfg') }}

      - name: Prepare commit.txt
        env:
          GITHUB_TOKEN: ${{ secrets.BUILDER_TOKEN }}
        run: |
          # ref. pypa/pip#8180
          # default ubuntu install does not include wheel, thus... install it right here
          python -mpip install -U pip wheel
          pip install .
          # personalized token is required, since we trigger a commit on success
          # and gh actions won't trigger another event when it is the default one
          espurna_nightly prepare ${{ github.event.inputs.target_repo }} ${{ github.repository }}
