on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    outputs:
      previous-commit: ${{ steps.commit.outputs.previous }}
      current-commit: ${{ steps.commit.outputs.current }}
      tag: ${{ steps.commit.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: nightly

      - id: commit
        run: |
          echo "::set-output name=tag::"$(git log --date="format:%Y%m%d" --format="%ad" -n 1)
          echo "::set-output name=previous::"$(git show HEAD~1:commit.txt)
          echo "::set-output name=current::"$(git show HEAD:commit.txt)

  actual-work:
    needs: [test]
    runs-on: ubuntu-20.04
    steps:
      - run: |
          printf 'Compare url is: https://github.com/xoseperez/espurna/compare/%s...%s\n' \
             ${{ needs.test.outputs.previous-commit }} \
             ${{ needs.test.outputs.current-commit }}
          printf 'Builder tag would be %s\n' ${{ needs.test.outputs.tag }}
