on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    outputs:
      current-commit: ${{ steps.commit.current }}
      previous-commit: ${{ steps.commit.previous }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: nightly
          path: nightly

      - run: |
          git --no-pager log --format=oneline
          git show HEAD~1:commit.txt
          git show HEAD:commit.txt

      - id: commit
        run: |
          echo "::set-output name=previous::"$(git show HEAD~1:commit.txt)
          echo "::set-output name=current::"$(git show HEAD:commit.txt)

  actual-work:
    needs: [test]
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "Nightly commit is "${{ needs.test.outputs.current-commit }}
          echo "Previous commit is "${{ needs.test.outputs.previous-commit }}
